# Generated by Django 5.1.7 on 2025-04-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
